{"metadata": {"signature": "sha256:f7d466c2ed230cf9e1b66ebdccb233664aff93ba515096231864f28894ecf904"}, "nbformat": 3, "nbformat_minor": 0, "worksheets": [{"cells": [{"cell_type": "markdown", "id": "19C7B1C2991A42AEA909D16F0EAF715A", "metadata": {}, "source": "# \u6c42\u52a9\uff1a\u60f3\u8981\u5bfb\u627e6\u6708\u4ee5\u6765\u8dcc\u5e45\u6700\u5927\u7684\u80a1\u7968\u7136\u540e\u5efa\u7acb\u4e00\u4e2a\u65b0\u7684DataFrame\uff0c\u4e3a\u4f55\u4e0d\u884c\u5440\u3002\u3002\u3002\u3002\uff1f\uff1f"}, {"cell_type": "code", "collapsed": false, "input": "import numpy as np\nimport pandas as pd\n\nuniverse = set_universe('A')\ncount_stock = 0   # how many stocks existed in my function\nlist = pd.DataFrame()\n\n\nfor i in range(len(universe)):\n    stock = DataAPI.MktEqudAdjGet(secID=universe[1], beginDate =\"20150601\", field = ['secID','secShortName' ,'tradeDate','openPrice','closePrice'])\n    stock = stock[stock.openPrice>0]\n    decline_rate = round((stock.closePrice.max() - stock.closePrice.min())/stock.closePrice.max()*100.0, 2)\n    data = [stock.secID[0],decline_rate]\n    list = list.append(data, ignore_index=True)", "language": "python", "metadata": {}, "outputs": [{"ename": "TypeError", "evalue": "'DataFrame' object is not callable", "output_type": "pyerr", "traceback": ["Traceback (most recent call last):\n", "  File \"python2.7/site-packages/IPython/kernel/zmq/ipkernel.py\", line 410, in execute_request\n    shell.run_cell(code, store_history=store_history, silent=silent)\n", "  File \"python2.7/site-packages/IPython/core/interactiveshell.py\", line 2748, in run_cell\n    interactivity=interactivity, compiler=compiler)\n", "  File \"python2.7/site-packages/IPython/core/interactiveshell.py\", line 2856, in run_ast_nodes\n    self.showtraceback()\n", "  File \"python2.7/site-packages/IPython/core/interactiveshell.py\", line 1756, in showtraceback\n    value, tb, tb_offset=tb_offset)\n", "  File \"python2.7/site-packages/IPython/core/ultratb.py\", line 1190, in structured_traceback\n    self, etype, value, tb, tb_offset, context)\n", "  File \"python2.7/site-packages/IPython/core/ultratb.py\", line 1098, in structured_traceback\n    self, etype, value, tb, tb_offset, context\n", "  File \"python2.7/site-packages/IPython/core/ultratb.py\", line 978, in structured_traceback\n    ipinst = get_ipython()\n", "  File \"python2.7/site-packages/IPython/core/getipython.py\", line 22, in get_ipython\n    from IPython.core.interactiveshell import InteractiveShell\n", "  File \"/home/ipython/abe10f7e5afbbb3a79ce619739541149/.ipython/profile_nbserver/startup/patch.py\", line 172, in mercury_import\n    fromlist = list(fromlist)\n", "TypeError: 'DataFrame' object is not callable\n"]}], "trusted": true}, {"cell_type": "code", "collapsed": false, "input": "a", "language": "python", "metadata": {}, "outputs": [], "trusted": true}, {"cell_type": "code", "collapsed": false, "input": "", "language": "python", "metadata": {}, "outputs": [], "trusted": true}], "metadata": {}}]}