# 回测运行正常，模拟交易却提示失败，求解答！

回测运行正常，模拟交易却提示失败，求解答！
策略日志提示如下：

2015-11-04 09:23 [SYS ERROR] handle_data函数运行失败，今天无法生成信号: handle_data() internal error line 45, in handle_data File "python2.7/site-packages/DataAPI/DATAYES.py", line 1964, in MktStockFactorsOneDayGet raise Exception((u'%s for request: %s' % (csvString if csvString is not None else 'Network Error', ''.join(requestString))).encode('utf-8')) Exception: -1:No Data Returned for request: /api/market/getStockFactorsOneDay.csv?appname=mercury&tradeDate=20151104&secID=000630.XSHE,600369.XSHG,002344.XSHE,601216.XSHG,600648.XSHG,601857.XSHG,002051.XSHE,600373.XSHG,000061.XSHE,002001.XSHE,600418.XSHG,600111.XSHG,601118.XSHG,600340.XSHG,000338.XSHE,002007.XSHE,000538.XSHE,600067.XSHG,000024.XSHE,600252.XSHG,600718.XSHG,002450.XSHE,002252.XSHE,600011.XSHG,000783.XSHE,600998.XSHG,300059.XSHE,600066.XSHG,601088.XSHG,002129.XSHE,000629.XSHE,002008.XSHE,000826.XSHE,000425.XSHE,600316.XSHG,000069.XSHE,600489.XSHG,600332.XSHG,600597.XSHG,601377.XSHG,601699.XSHG,600048.XSHG,600958.XSHG,603288.XSHG,601992.XSHG,000156.XSHE,000027