# 遇到错误后，所有策略和代码均不能正确运行了……

调策略过程中遇到错误再也无法恢复了，所有正确策略均提示错误, 以下是错误的提示，怎么改都是这个：


```python

ValueError                                Traceback (most recent call last)
<mercury-input-2-e2dc7445257e> in <module>()
    157                                                     slippage        = slippage,
    158                                                     refresh_rate    = refresh_rate,
--> 159                                                     freq            = freq)
    160         perf = quartz.perf_parse(bt, quartz_acct)
    161     elif QUARTZ_CACHE.get('start', 0) == sim_params.first_trading_day and          QUARTZ_CACHE.get('end', 0) == sim_params.last_trading_day and          QUARTZ_CACHE.get('benchmark', 0) == sim_params.benchmark and          QUARTZ_CACHE.get('universe', 0) == sim_params.universe:

python2.7/site-packages/quartz/backtest.pyc in backtest_generator(start, end, benchmark, universe, capital_base, initialize, handle_data, security_base, commission, slippage, refresh_rate, freq, *args, **kwargs)
    293             raise ValueError("Start date of intraday backtest must not be earlier than 2009-01-01!")
    294 
--> 295         idxmap_all, data_all = data_generator.get_daily_data(sim_params, fq=False)
    296         data_daily_gen = data_generator.get_daily_data_generator(data_all)
    297         account = env.Account(sim_params, strg, idxmap_all, data_all, commission, slippage)

python2.7/site-packages/quartz/sim_condition/data_generator.pyc in get_daily_data(sim_params, fq)
     37         data_all += data_fd
     38     elif stocks:
---> 39         idxmap_univ, idxmap_sc, data_all = load_stocks_data(stocks, trading_days, fq)
     40     elif funds:
     41         idxmap_univ, idxmap_sc, data_all = load_funds_data(funds, trading_days, fq)

python2.7/site-packages/quartz/data/equity.pyc in load_stocks_data(universe, trading_days, fq)
    107                     continue
    108 
--> 109                 line = map(float, line[2:])
    110                 if len(universe) == 0:
    111                     i_date = idxmap_date[date]

> > ValueError: could not convert string to float: 
```