# 关于winsorize函数

运行几次都是这样
```python
2016-02-15 10:50 [SYS ERROR] handle_data函数运行失败，今天无法生成信号: handle_data() internal error line 26, in handle_data File "quartz_live/ext/MFHandler/SignalProcess.py", line 120, in winsorize raw_data_check(raw_data) File "quartz_live/ext/MFHandler/Exception.py", line 92, in raw_data_check raise InputTypeError('Input raw_data key length error') InputTypeError: Input raw_data key length error

2016-02-15 10:50 [SYS INFO] 策略初始化成功
```