# 将数据写入excel文件出现这个报错？

import pandas as pd
MarketEqud=DataAPI.MktEqudGet(secID = "000002.XSHE", beginDate = "20130106", endDate = "20140110")
MarketEqud.to_excel('test1.xls','Sheet1',)   
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
&lt;mercury-input-6-69af17e22820&gt; in &lt;module&gt;()
      2 import pandas as pd
      3 MarketEqud=DataAPI.MktEqudGet(secID = "000002.XSHE", beginDate = "20130106", endDate = "20140110")
----&gt; 4 MarketEqud.to_excel('test1.xls','Sheet1',)

python2.7/site-packages/pandas/core/frame.pyc in to_excel(self, excel_writer, sheet_name, na_rep, float_format, columns, header, index, index_label, startrow, startcol, engine, merge_cells, encoding, inf_rep)
   1267                                  startrow=startrow, startcol=startcol)
   1268         if need_save:
-&gt; 1269             excel_writer.save()
   1270 
   1271     def to_stata(

python2.7/site-packages/pandas/io/excel.pyc in save(self)
   1173         Save workbook to disk.
   1174         """
-&gt; 1175         return self.book.save(self.path)
   1176 
   1177     def write_cells(self, cells, sheet_name=None, startrow=0, startcol=0):

python2.7/site-packages/xlwt/Workbook.pyc in save(self, filename)
    660 
    661         doc = CompoundDoc.XlsDoc()
--&gt; 662         doc.save(filename, self.get_biff_data())
    663 
    664 

python2.7/site-packages/xlwt/Workbook.pyc in get_biff_data(self)
    635         all_links          = self.__all_links_rec()
    636 
--&gt; 637         shared_str_table   = self.__sst_rec()
    638         after = country + all_links + shared_str_table
    639 

python2.7/site-packages/xlwt/Workbook.pyc in __sst_rec(self)
    597 
    598     def __sst_rec(self):
--&gt; 599         return self.__sst.get_biff_record()
    600 
    601     def __ext_sst_rec(self, abs_stream_pos):

python2.7/site-packages/xlwt/BIFFRecords.pyc in get_biff_record(self)
     74                 s = u''
     75             if isinstance(s, str) or isinstance(s, unicode):
---&gt; 76                 self._add_to_sst(s)
     77             else:
     78                 self._add_rt_to_sst(s)

python2.7/site-packages/xlwt/BIFFRecords.pyc in _add_to_sst(self, s)
     89 
     90     def _add_to_sst(self, s):
---&gt; 91         u_str = upack2(s, self.encoding)
     92 
     93         is_unicode_str = u_str[2] == '\x01'

python2.7/site-packages/xlwt/UnicodeUtils.pyc in upack2(s, encoding)
     48         us = s
     49     else:
---&gt; 50         us = unicode(s, encoding)
     51     # Limit is based on number of content characters
     52     # (not on number of bytes in packed result)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)

管理员同志们烦请解答一下，我错在哪里了，谢谢