# in handle_data KeyError: u'002204.XSHE'

策略日志显示：


```python
2016-07-01 09:13 [SYS ERROR]
python handle_data函数运行失败，今天无法生成信号: handle_data() internal error line 29, in handle_data KeyError: u'002204.XSHE'
```

2016-06-28 14:53 [SYS INFO] 策略初始化成功