# 最近的策略运行有什么问题吗？

之前克隆了几个别人的进行研究，在回测时都正常。但中秋节后就都不行了。所有的都不能正常回测。
然后模拟实盘那里也不行了。[SYS ERROR] handle_data函数运行失败，今天无法生成信号: handle_data() internal error line 25, in handle_data File "quartz/simulation/live_account.py", line 833, in get_attribute_history return self._get_daily_attribute_history(attribute, time_range) File "quartz/simulation/live_account.py", line 908, in _get_daily_attribute_history raise ValueError('History overflow. Your current max daily history window is {}. Please use a shorter parameter, or change max_history_window in your initialize()!'.format(self._sim_params._max_history_window_daily)) ValueError: History overflow. Your current max daily history window is 30. Please use a shorter parameter, or change max_history_window in your initialize()!
请问要如何解决呀？