# datetime.date 比较错误

from datetime import date
from CAL.PyCAL import *

cal = Calendar('China.SSE')
start=date(2010,1,1)
end=date(2017,1,1)
while start&lt;end:
    print(start)
    start=cal.advanceDate(start,'1m')
    
结果是以下错误：

2010-01-01
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
&lt;mercury-input-46-9617D4390AFD4AD883D29059B36A24E8&gt; in &lt;module&gt;()
      7 start=date(2010,1,1)
      8 end=date(2017,1,1)
----&gt; 9 while start&lt;end:
     10     print(start)
     11     start=cal.advanceDate(start,'1m')

/home/ipython/anaconda/lib/python2.7/site-packages/CAL/DateUtilities/Dates.pyc in __lt__(self, date2)
    117 
    118     def __lt__(self, date2):
--&gt; 119         return self.__impl__ &lt; date2.__impl__
    120 
    121     def __le__(self, date2):

AttributeError: 'datetime.date' object has no attribute '__impl__'

有些莫名奇妙，有人遇到过吗？