# 报告斑竹：发现500指数的分钟数据好像有误

start = '2017-04-07'                       # 回测起始时间
end = '2017-04-08' 
freq = 'm'                                 # 'd'表示使用日频率回测，'m'表示使用分钟频率回测
refresh_rate = 1  
universe = ['000905.ZICN'] 

def handle_data(account):   
	if  account.now.hour==10 and account.now.minute==29:
		close_price  = account.get_attribute_history('closePrice', 60)#把今天的前60分钟的数据拿到
    	print close_price['000905.ZICN'] 
        
        
6554.257, 6546.744, 6547.602, 6550.073, 6549.968, 6551.058, 6551.822, 6553.353, 6552.621, 6551.618, 6549.696, 6549.47 , 6551.472, 6556.066, 6558.095, 6558.423, 6558.515, 6560.028, 6560.338, 6559.424, 6557.897, 6557.582, 6557.701, 6557.668, 6558.808, 6560.196, 6560.769, 6559.284, 6558.006, 6555.479, 6554.184, 6551.1 , 6548.658, 6547.43 , 6547.657, 6547.045, 6547.255, 6547.443, 6546.463, 6546.049, 6545.873, 6546.084, 6545.725, 6546.045, 6548.997, 6551.985, 6553.402, 6553.833, 6553.886, 6554.109, 6553.658, 6554.588, 6556.858, 6558.019, 6558.599, 6558.856, 6559.301, 6558.882, 6558.588, 6558.933

和实际情况都有微小误差。有没有程序员能帮忙看看？
