# 新建策略 运行就报错 ？

新建策略 运行就报错 ？
```
ImportError                               Traceback (most recent call last)
<mercury-input-1-A1CF6C357A17497A8BA4BD4D442E966B> in <module>()
----> 1 from quartz.api import *;from quartz.trade.cost import Slippage,Commission
      2 try:
      3     DataAPI.set_client_info("strategy")
      4 except:
      5     pass

/srv/data/datas/build/bdist.linux-x86_64/egg/quartz/__init__.py in <module>()

/srv/data/datas/build/bdist.linux-x86_64/egg/quartz/api.py in <module>()

/srv/data/datas/build/bdist.linux-x86_64/egg/quartz/utils/__init__.py in <module>()

/srv/data/datas/build/bdist.linux-x86_64/egg/quartz/utils/data_utils.py in <module>()

/srv/data/datas/build/bdist.linux-x86_64/egg/quartz/data_loader/__init__.py in <module>()

/srv/data/datas/build/bdist.linux-x86_64/egg/quartz/data_loader/market_loader.py in <module>()

/srv/data/datas/build/bdist.linux-x86_64/egg/quartz/data_loader/data_api.py in <module>()

/home/ipython/anaconda/lib/python2.7/site-packages/DataAPI/__init__.py in <module>()
     25 from .OTHER import *
     26 from .DataCube import *
---> 27 from . import DataCube
     28 try:
     29     import __builtin__

ImportError: cannot import name DataCube
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<mercury-input-1-A1CF6C357A17497A8BA4BD4D442E966B> in <module>()
      1 start = '2017-01-01'                       # 回测起始时间
      2 end = '2018-01-01'                         # 回测结束时间
----> 3 universe = DynamicUniverse('HS300')        # 证券池，支持股票、基金、期货、指数四种资产
      4 benchmark = 'HS300'                        # 策略参考标准
      5 freq = 'd'                                 # 策略类型，'d'表示日间策略使用日线回测，'m'表示日内策略使用分钟线回测

NameError: name 'DynamicUniverse' is not defined
```